esphome:
  name: acculevel-modbus

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
    level: INFO
    baud_rate: 0

# Enable Home Assistant API
api:
  password: "password123"

ota:
  password: "password123"

wifi:
  ssid: !secrets wifi_ssid
  password: !secrets wifi_pass
  domain: !secrets iot_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Acculevel-Modbus"
    password: "pEik53pvVPwr"

captive_portal:
    
# Example configuration entry
uart:
  ...

modbus:
  flow_control_pin: GPIOXX
  id: modbus1

modbus_controller:
- id: modbus_device
  address: 0x1   ## address of the Modbus slave device on the bus
  modbus_id: modbus1
  setup_priority: -10

sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Battery Capacity"
  register_type: holding
  address: 0x9001    ## address of the register inside the Modbus slave device
  unit_of_measurement: "AH"
  value_type: U_WORD

switch:
- platform: modbus_controller
  modbus_controller_id: modbus_device
  name: "Reset to Factory Default"
  register_type: coil
  address: 0x15
  bitmask: 1

text_sensor:
- name: "rtc_clock"
  platform: modbus_controller
  modbus_controller_id: modbus_device
  id: rtc_clock
  internal: true
  register_type: holding
  address: 0x9013
  register_count: 3
  raw_encode: HEXBYTES
  response_size: 6