esphome:
  name: rack-monitor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "password123"

ota:
  password: "password123"

wifi:
  ssid: !secrets wifi_ssid
  password: !secrets wifi_pass
  domain: !secrets iot_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rack-Monitor Fallback Hotspot"
    password: "uEwcFyhdiRbe"

captive_portal:

web_server:
  port: 80
    
switch:
  - platform: gpio
    id: builtIn_led
    name: "Built In Led"
    pin:
      number:  D4
      inverted:  True
  - platform: gpio
    pin: D0
    id: ntc_vcc
#######
sensor:
  -  platform:  ntc
     sensor:  resistance_sensor
     name:  NTC Temperature B Constant
     calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm
    
  -  platform:  resistance
     id:  resistance_sensor
     sensor:  source_sensor
     configuration:  DOWNSTREAM
     resistor:  10kOhm
     reference_voltage:  3.3V
     name:  Resistance Sensor
     
  -  platform:  adc
     id:  source_sensor
     filters:
       -  offset:  -0.042
       -  multiply: 3.3
     pin:  A0
     update_interval: never

interval:
  - interval: 1s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc