esphome:
  name: rack-monitor

esp32:
  board: esp32doit-devkit-v1

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "password123"

ota:
  password: "password123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: !secret iot_domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rack-Manager Fallback Hotspot"
    password: "uEwcFyhdiRbe"

captive_portal:

web_server:
  port: 80

switch:
  # - platform: gpio
  #   id: builtIn_led
  #   name: "Built In Led"
  #   pin:
  #     number: GPIO02 # PIIO_NONE
  #     inverted: True
  - platform: gpio
    pin:
      number: GPIO02 # PIIO_NONE
      inverted: True
    id: ntc_vcc
#######
sensor:
  - platform: ntc
    id: ntc_1
    sensor: resistance_sensor
    name: NTC Temperature B Constant
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    reference_voltage: 3.3V
    name: Resistance Sensor

  - platform: adc
    id: source_sensor
    filters:
      - offset: -0.035
      # - offset: -0.042
      - multiply: 3.3
    pin: GPIO35 # A7 # PIIO24
    update_interval: never

  - platform: template
    name: Temperature F
    id: temperature_f
    lambda: return id(ntc_1).state * 9/5+32;
    update_interval: 1s

interval:
  - interval: 1s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc

output:
  - platform: ledc
    id: motor_forward_pin
    pin: GPIO14
  - platform: ledc
    id: motor_reverse_pin
    pin: GPIO27
  - platform: ledc
    id: motor_speed_pin
    pin: GPIO12

# Fan configuration entry
fan:
  - platform: hbridge
    id: in_fan
    name: "Intake Fan"
    pin_a: motor_forward_pin # A16 # 14 / PI 05
    pin_b: motor_reverse_pin # 26 / PI 26 
    enable_pin: motor_speed_pin # 12 / PI 06 
    decay_mode: slow   # slow decay mode (coasting) or fast decay (braking).